#!/bin/bash
# Process properties.csv to get property tags
cat << END_HEADER > PropertyTags.java
// DO NOT EDIT THIS FILE
// Automatically generated on $(date) by pstreader/extras/getpropertytags.sh
// Any changes must be made to that file.
package io.github.jmcleodfoss.pst;

/** Known Property tags
*	@see <a href="https://github.com/Jmcleodfoss/pstreader/blob/master/extras/properties.csv">pstreader properties.pst</a>
*	@see <a href="https://github.com/Jmcleodfoss/msgreader/blob/master/extras/getpropertytags.sh">getpropertytags.sh</a>
*	@see <a href="https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148">MS-OXPROPS</a>
*/

public class PropertyTags
{

	// Properties related to named properties. These are defined in MS-PST rather than in MS-OXPROPS.
	static final short NameidBucketCount = 0x0001;
	static final short NameidStreamGuid = 0x0002;
	static final short NameidStreamEntry = 0x0003;
	static final short NameidStreamString = 0x0004;
	static final short NameToIdMapBucketFirst = 0x1000;
	static final short NameToIdMapBucketLast = 0x2fff;

	static final short NamedPropertyFirst = (short)0x8000;
	static final short NamedPropertyLast = (short)0x8fff;

END_HEADER
sort -t , -k 2 properties.csv | sed '
	${
		i\

		i\
	static final java.util.HashMap<Integer, String> tags = new java.util.HashMap<Integer, String>();
		i\
	static {
		g
		a\
	}
	}
	/^PidTag\([^,]*\),\([^,]*\),\([^,]*\),0x\(.*\),,$/s//\	static final public int \1 = \2\4;/p
	/^.*static final public int \([^ ]*\).*$/{
		s//\	\	tags.put(\1, "\1");/
		H
		d
	}
	/n\/a/d
	/^PidLid/d
	' >> PropertyTags.java

cat << END_FOOTER >> PropertyTags.java

	public static void main(String[] args)
	{
		java.util.Iterator<Integer> iter = PropertyTags.tags.keySet().iterator();
		while (iter.hasNext()) {
			Integer t = iter.next();
			System.out.printf("0x%08x: %s\n", t, PropertyTags.tags.get(t));
		}
	}
}
END_FOOTER
